- name: Download latest WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0755'

- name: Ensure documentroot exists
  file:
    path: /var/www/{{ inventory_hostname }}/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Extract WordPress directly to document root
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/{{ inventory_hostname }}/
    remote_src: yes
    creates: /var/www/{{ inventory_hostname }}/index.php

- name: Set correct ownership for WordPress
  file:
    path: /var/www/{{ inventory_hostname }}
    recurse: yes
    owner: www-data
    group: www-data

- name: Set directory permissions
  find:
    paths: /var/www/{{ inventory_hostname }}
    file_type: directory
  register: wordpress_dirs

- name: Set permissions 755 for directories
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ wordpress_dirs.files }}"

- name: Set file permissions
  find:
    paths: /var/www/{{ inventory_hostname }}
    file_type: file
  register: wordpress_files

- name: Set permissions 644 for files
  file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ wordpress_files.files }}"

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/{{ inventory_hostname }}/wp-config.php
    owner: www-data
    group: www-data
    mode: '0755'
